Program Nhap_chuoi;
Var
   Holot: String[10];
   Ten  : String[5];
Begin
	Writeln('Ban chi nhap Holot=10, Ten=5 ky tu');
   Write('-Cho biet ho lot: ');
   Readln(holot);
   Write('-Cho biet ten: ');
   Readln(Ten);
   Writeln(holot);
   Write('');
   Write(ten);
   Writeln;
   Writeln('Neu ban nhap Holot > 10, Ten > 5 ky tu thi');
   Write('-Cho biet ho lot: ');
   Readln(holot);
   Write('-Cho biet ten: ');
   Readln(Ten);
   Writeln(holot);
   Write('');
   Write(ten);
   Readln
End.
