Program Cac_ham_cua_Boolean;
Begin
	Writeln('CAC HAM CUA KIEU BOOLEAN');
   Writeln('------------------------');
   Writeln('Ord(False) --------> ',Ord(false));
   Writeln('Ord(True)  --------> ',Ord(True));
   Writeln('Pred(True) --------> ',Pred(True));
   Writeln('Pred(False)--------> ',Pred(False));
   Writeln('Succ(False)--------> ',Succ(False));
   Writeln('Succ(True) --------> ',Succ(True));
   Readln
End.