Program Cac_ham_so_thuc;
Begin
	Writeln('CAC HAM TOAN HOC KIEU SO THUC');
   Writeln('-----------------------------');
   Writeln('Round(3.141592) --------> ',Round(3.141592));
   Writeln('Trunc(3.141592) --------> ',Trunc(3.141592));
   Writeln('Frac(3.141592)  --------> ',Frac(3.141592));
   Writeln('Abs(-5.5)      --------> ',Abs(-5.5));
   Writeln('Sqr(12)        --------> ',Sqr(12));
   Writeln('Sqrt(144)      --------> ',Sqrt(144));
   Writeln('Ln(2)          --------> ',Ln(2));
   Writeln('Exp(2)         --------> ',Exp(2));
   Writeln('Sin(45*pi/180) --------> ',Sin(45*pi/180));
   Writeln('Cos(45*pi/180) --------> ',Cos(45*pi/180));
   Writeln('Arctan(45*pi/180)------> ',Arctan(45*pi/180));
   Writeln('Tri cua Pi     --------> ',Pi);
   Writeln('  Bam phim bat ky de ket thuc');
   Readln
End.