Program Chuyen_doi_kieu_tu_dong;
Var
	a,b:Integer;
   c:Real;
Begin
	Writeln('BIEN DOI KIEU TU DONG');
   Writeln('---------------------');
   Writeln('A,B thuoc kieu Integer');
   Writeln('C Thuoc kieu Real');
   Writeln;
	a:=20;
   b:=10;
   c:=a+b;
   Writeln('Phep cong C = A + B = ',c:12:10);
   Writeln;
   Writeln('A,B da tu dong doi thanh kieu Real');
   Writeln('     Bam phim <Enter> de ket thuc');
   Readln
End.