Program Cac_ham_toan_hoc;
Begin
	Writeln('Pred(5) -----------> ',Pred(5):6);
   Writeln('Succ(5) -----------> ',Succ(5):6);
   Writeln('Abs(-5) -----------> ',Abs(-5):6);
   Writeln('Abs(-5.5) -----------> ',Abs(-5.5):6:2);
   Writeln('Sqr(10) -----------> ',Sqr(10):6);
   Writeln('Sqrt(16) -----------> ',Sqrt(16):6:2);
   Writeln('Odd(3) -----------> ',Odd(3));
   Writeln('Odd(4) -----------> ',Odd(4));
   Writeln('Ln(2) -----------> ',Ln(2):6:2);
   Writeln('Exp(2) -----------> ',Exp(2):6:2);
   Writeln('Trunc(3.1415) -----------> ',Trunc(3.1415):6);
   Writeln('Round(56.678) -----------> ',Round(56.678):6);
   Writeln('Round(56.421) -----------> ',Round(56.421):6);
   Writeln('Round(-56.678) -----------> ',Round(-56.678):6);
   Writeln('Tri so cua hang Pi --------> ',Pi:10:8);
   Writeln('Sin(45*pi/180) -----------> ',Sin(45*pi/180):6:2);
   Writeln('Cos(45*pi/180) -----------> ',Cos(45*pi/180):6:2);
   Writeln('Arctan(45*pi/180) -----------> ',Arctan(45*pi/180):6:2);
   Writeln('   Bam phim <Enter> de ket thuc');
   Readln
End.