Program Phep_toan_Boolean;
Begin
	Writeln('MINH HOA CAC PHEP TOAN KIEU BOOLEAN');
   Writeln('-----------------------------------');
   Writeln('-Cac phep toan quan he:');
   Writeln('5 = 6 -----------> ',5=6);
   Writeln('5 > 6 -----------> ',5>6);
   Writeln('5 >= 6 ----------> ',5>=6);
   Writeln('5 < 6 -----------> ',5<6);
   Writeln('5 <= 6 ----------> ',5<=6);
   Writeln('5 <> 6 ----------> ',5<>6);
   Writeln('-Cac phep toan logic:');
   Writeln('FALSE AND FALSE -------> ',FALSE AND FALSE);
   Writeln('FALSE AND TRUE --------> ',FALSE AND TRUE);
   Writeln('TRUE AND FALSE --------> ',TRUE AND FALSE);
   Writeln('TRUE AND TRUE ---------> ',TRUE AND TRUE);
	Writeln('FALSE OR FALSE -----------> ',FALSE OR FALSE);
   Writeln('FALSE OR TRUE ------------> ',FALSE OR TRUE);
   Writeln('TRUE OR FALSE ------------> ',TRUE OR FALSE);
   Writeln('TRUE OR TRUE -------------> ',TRUE OR TRUE);
   Writeln('FALSE XOR FALSE -------> ',FALSE XOR FALSE);
   Writeln('FALSE XOR TRUE --------> ',FALSE XOR TRUE);
   Writeln('TRUE XOR FALSE --------> ',TRUE XOR FALSE);
   Writeln('TRUE XOR TRUE ---------> ',TRUE XOR TRUE);
   Writeln('NOT FALSE   -------------> ',NOT FALSE);
   Writeln('NOT TRUE    -------------> ',NOT TRUE);
   Readln
End.