Program Ham_thu_tuc_ky_tu;
Begin
	Writeln('CAC HAM, THU TUC KY TU');
   Writeln('----------------------');
   Writeln('Ord(''A'') -------> ',Ord('A'));
   Writeln('Chr(65)  -------> ',Chr(65));
   Writeln('#(65)  ---------> ',#65);
   Writeln('Chr(Ord(''A'')) ---> ',Chr(Ord('A')));
   Writeln('Ord(Chr(65)) ----> ',Ord(Chr(65)));
   Writeln('Pred(''B'')  -----> ',Pred('B'));
   Writeln('Succ(''B'')  -----> ',Succ('B'));
   Writeln('Upcase(''a'')  ---> ',Upcase('a'));
   Readln
End.