Program For_long_nhau;
Var
	m,n,i,j:Byte;
Begin
	Writeln('VE HINH CHU NHAT BANG DAU SAO');
   Writeln('-----------------------------');
   Write('-Nhap chieu dai: ');
   Readln(m);
   Write('-Nhap chieu rong: ');
   Readln(n);
   For i:=1 To N Do
   	Begin
      	For j:=1 To M Do
         	Write('*');
            Writeln;
      End;
	Writeln;
   Writeln('  Bam phim <Enter> de ket thuc');
   Readln
End.